services:
  trainer:
    build:
      context: .
      dockerfile: trainer/Dockerfile

    volumes:
      # Code
      - .:/workspace

      # RAW Daten
      - ./data:/data/raw

      # konvertierte Daten
      - ./data_lerobot:/data/processed

      # pretrained Modell
      - ./modell:/models

      # checkpoints
      - ./checkpoints:/checkpoints

      # finale Modelle
      - ./output:/output

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=all

    command: bash trainer/train.sh